name: E2E tests

on:
  pull_request:
    branches:
      - main
      - v*
    paths:
      - "**.go"
      - "chart/**"
      - "Dockerfile"
      - "test/e2e/**"
      - ".github/workflows/e2e-tests.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  e2e:
    name: Run e2e suite
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'loft-sh' # do not run on forks
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: test/e2e/go.mod
          cache: false

      - name: Set up Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1

      - name: Run e2e tests
        working-directory: test/e2e
        run: go test ./... -v -timeout 20m
